version: '3'

services:
  api:
    build:
      dockerfile: './Dockerfile.dev'
      context: .
    restart: always
    container_name: api
    command: 'npm run start:dev'
    ports:
      - '1337:1337'
    networks:
      - todo-app-network
    depends_on:
      - postgres
    volumes:
      - './src/:/opt/data/src'

  postgres:
    image: postgres:16.2
    container_name: postgres_db
    ports:
      - '5432:5432'
    networks:
      - todo-app-network
    environment:
      POSTGRES_DB: todo-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  todo-app-network:
    driver: bridge

volumes:
  postgres_data:
